spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: 1234
  application:
    name: kafka-connect-application
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: application-connect